#!/bin/bash
# envvars - default environment variables for apache2ctl

# this won't be correct after changing uid
unset HOME

# Since there is no sane way to get the parsed apache2 config in scripts, some
# settings are defined via environment variables and then used in apache2ctl,
# /etc/init.d/apache2, /etc/logrotate.d/apache2, etc.

export NPG_APACHE_HOST=`hostname`
export APACHE_RUN_USER=${USER}
export APACHE_RUN_GROUP=solexa
export NPG_TRACKING_SERVER_PATH=$(dirname $(dirname $APACHE_CONFDIR))
echo "Server path: ${NPG_TRACKING_SERVER_PATH}"
export APACHE_RUN_DIR=${NPG_TRACKING_SERVER_PATH}

export dev='dev'
if [[ "$NPG_TRACKING_SERVER_PATH" =~ "www-live" ]] ; then dev='live'; fi;
echo "dev: ${dev}"

export APACHE_LOG_DIR=${NPG_TRACKING_SERVER_PATH}/logs

echo "Log directory: ${APACHE_LOG_DIR}"
export APACHE_PID_FILE=${APACHE_LOG_DIR}/apache_${NPG_APACHE_HOST}_${dev}.pid
export APACHE_LOCK_DIR=${NPG_TRACKING_SERVER_PATH}/lock
## The locale used by some modules like mod_dav
export LANG=C
## Uncomment the following line to use the system default locale instead:
#. /etc/default/locale

export LANG

export ORACLE_HOME=/software/oracle-ic-11.2

## The command to get the status for 'apache2ctl status'.
## Some packages providing 'www-browser' need '--dump' instead of '-dump'.
#export APACHE_LYNX='www-browser -dump'

## If you need a higher file descriptor limit, uncomment and adjust the
## following line (default is 8192):
#APACHE_ULIMIT_MAX_FILES='ulimit -n 65536'

