#!/usr/bin/env perl
my $VAR1 = {
  'staging_areas' => {
    'prefix' => '/tmp/esa-sv-*'
  },
  'staging_areas2webservers' => {
    'default' => {'npg_tracking' => 'http://some.san.ac.uk:678',
                  'seqqc'        => 'http://some.san.ac.uk:999'},
    'esa-sv' => {'npg_tracking'  => 'http://esa-sv.dnap.san.ac.uk:678',
                 'seqqc'         => 'http://esa-sv.dnap.san.ac.uk:999'},
  },
  'repository' => {
    'root' => '/lustre/scratch109/srpipe/',
    'instrument_prefix' => 'C:\Illumina\MiSeq Reporter\Genomes\WTSI_references'
  },
  'users' => {
    'production' => [qw/userone usertwo/],
  },
  'mock' =>'mock entry to test that we are reading this file',
}
