#!/usr/bin/env perl

my $VAR1 = {
                               'dbattr' => {
                                             'mysql_enable_utf8' => 1
                                           },
                               'dbuser' => 'warehouse_ro',
                               'dsn' => 'dbi:mysql:host=mcs12;database=sequencescape_warehouse;port=3379',
};

